import React from 'react'
import Dummy from '../src/assests/index'

const page = () => {
  return (

    // <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    <>
      <p>Hello Dear</p>
      <Dummy/>
      
      <p className='text-red-700' >Hello! Fellow Developer</p>
    </>
  )
}

export default page
