import React from 'react'
import { About, Explore, FeedBack, GetStarted, Hero, Insights, WhatsNew, World } from '../src/segments'


const page = () => {
  return (

    // <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    
    
    <>
   

        <Hero/>
        <div className="relative">
        <About/>
        <div className="gradient-03 z-0"/>
        <Explore/>
        </div>

        <div className="relative">
        <GetStarted/>
        <div className="gradient-04 z-0"/>
        <WhatsNew/>
        </div>

        <World/>
        
        
        <div className="relative">
        <Insights/>
        <div className="gradient-04 z-0"/>
        <FeedBack/>
        </div>

    </>
  )
}

export default page
