import React from 'react'
import { About, Explore, FeedBack, GetStarted, Hero, Insights, WhatsNew, World } from '../src/segments'


const page = () => {
  return (

    // <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    
    
    <>
   

        <Hero/>
        <About/>
        <Explore/>
        <GetStarted/>
        <WhatsNew/>
        <World/>
        <Insights/>
        <FeedBack/>

    </>
  )
}

export default page
